//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDNAPTRANS2018.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("577")]
        public int FrmWidth {
            get {
                return ((int)(this["FrmWidth"]));
            }
            set {
                this["FrmWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("666")]
        public int FrmHeight {
            get {
                return ((int)(this["FrmHeight"]));
            }
            set {
                this["FrmHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Werk\\RDNAPTRANS\\rdcorr2018.txt")]
        public string rdcorr2018 {
            get {
                return ((string)(this["rdcorr2018"]));
            }
            set {
                this["rdcorr2018"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Werk\\RDNAPTRANS\\nlgeo2018.txt")]
        public string nlgeo2018 {
            get {
                return ((string)(this["nlgeo2018"]));
            }
            set {
                this["nlgeo2018"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Werk\\RDNAPTRANS\\Z001_ETRS89andRDNAP.txt")]
        public string Z001_ETRS89andRDNAP {
            get {
                return ((string)(this["Z001_ETRS89andRDNAP"]));
            }
            set {
                this["Z001_ETRS89andRDNAP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Werk\\RDNAPTRANS\\002_ETRS89.txt")]
        public string Z002_ETRS89 {
            get {
                return ((string)(this["Z002_ETRS89"]));
            }
            set {
                this["Z002_ETRS89"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Werk\\RDNAPTRANS\\002_RDNAP.txt")]
        public string Z002_RDNAP {
            get {
                return ((string)(this["Z002_RDNAP"]));
            }
            set {
                this["Z002_RDNAP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("155000")]
        public double RDx {
            get {
                return ((double)(this["RDx"]));
            }
            set {
                this["RDx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("463000")]
        public double RDy {
            get {
                return ((double)(this["RDy"]));
            }
            set {
                this["RDy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double NAPh {
            get {
                return ((double)(this["NAPh"]));
            }
            set {
                this["NAPh"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ETRSlat {
            get {
                return ((double)(this["ETRSlat"]));
            }
            set {
                this["ETRSlat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ETRSlon {
            get {
                return ((double)(this["ETRSlon"]));
            }
            set {
                this["ETRSlon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double ETRSh {
            get {
                return ((double)(this["ETRSh"]));
            }
            set {
                this["ETRSh"] = value;
            }
        }
    }
}
